# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: moviesworkflow

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up NodeJs
        uses: actions/setup-node@v4
        with: 
            node-version: 22
        # cache: 'npm'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -f ./frontend/Dockerfile -t "movies:v1.0" --build-arg SKIP_NPM_INSTALL=true ./frontend
